CREATE TABLE dbo.USUARIO (
IDUsuario INT PRIMARY KEY IDENTITY (1, 1),
Apellidos NVARCHAR (50) NOT NULL,
Nombre NVARCHAR (20) NOT NULL,
FecNac DATE NOT NULL,
TipoUser BIT NOT NULL,
Email NVARCHAR (50) NOT NULL,
Premium BIT NOT NULL
);
go
CREATE TABLE dbo.PELICULAS (
IDPelicula INT PRIMARY KEY IDENTITY (1, 1),
Titulo NVARCHAR (50) NOT NULL,
Año DATE NOT NULL,
PuntMedia DECIMAL() NOT NULL,
Email NVARCHAR (50) NOT NULL,
Premium BIT NOT NULL
);
go
--CREATE TABLE dbo.LISTA (
--IDLista INT PRIMARY KEY IDENTITY (1, 1),
--Titulo NVARCHAR (20) NOT NULL,
--Publica BIT NOT NULL,
--Email NVARCHAR (50) NOT NULL,
--Premium BIT NOT NULL
--);
--go
