CREATE TABLE dbo.USUARIOS (
IDUsuario INT PRIMARY KEY IDENTITY (1, 1),
Apellidos NVARCHAR (50) NOT NULL,
Nombre NVARCHAR (20) NOT NULL,
FecNac DATE NOT NULL,
TipoUser BIT NOT NULL,
Email NVARCHAR (50) NOT NULL,
Premium BIT NOT NULL
);
go
CREATE TABLE dbo.PELICULAS (
IDPelicula INT PRIMARY KEY IDENTITY (1, 1),
Titulo NVARCHAR (50) NOT NULL UNIQUE,
Año DATE NOT NULL,
PuntMedia DECIMAL(2,1) NOT NULL,
Email NVARCHAR (50) NOT NULL,
Premium BIT NOT NULL
);
go
CREATE TABLE dbo.TRABAJADORES (
IDTrabajador INT PRIMARY KEY IDENTITY (1, 1),
Tipo INT NOT NULL,
Apellido NVARCHAR (50) NOT NULL,
Nombre NVARCHAR (20) NOT NULL,
FecNac DATE NOT NULL,
Pais NVARCHAR (50) NOT NULL
);
go
CREATE TABLE dbo.GENEROS (
IDGenero INT PRIMARY KEY IDENTITY (1, 1),
Nombre NVARCHAR (50) NOT NULL UNIQUE,
FecNac DATE NOT NULL,
Pais NVARCHAR (50) NOT NULL
);
go
CREATE TABLE dbo.SALAS (
IDSala INT PRIMARY KEY IDENTITY (1, 1),
Aforo INT NOT NULL,
Ciudad NVARCHAR (30) NOT NULL
);
go
CREATE TABLE dbo.LISTAS (
IDLista INT PRIMARY KEY IDENTITY (1, 1),
Titulo NVARCHAR (20) NOT NULL,
Publica BIT NOT NULL,
NElementos INT NULL,
PropietarioFK INT NOT NULL UNIQUE,
CONSTRAINT ListaPropietarioFK FOREIGN KEY (PropietarioFK)
REFERENCES USUARIOS(IDUsuario),
);
go
CREATE TABLE dbo.CRITICAS (
IDCritica INT PRIMARY KEY IDENTITY (1, 1),
Texto NVARCHAR (3000) NOT NULL,
IDUserFK INT NOT NULL,
IDPeliFK INT NOT NULL,
CONSTRAINT CriticaUserFK FOREIGN KEY (IDUserFK)
REFERENCES USUARIOS(IDUsuario),
CONSTRAINT CriticaPeliFK FOREIGN KEY (IDPeliFK)
REFERENCES PELICULAS(IDPelicula)
);
go
CREATE TABLE dbo.FUNCIONES (
IDFuncion INT PRIMARY KEY IDENTITY (1, 1),
Fecha DATETIME NOT NULL,
Disponibles INT NULL,
PrecioBruto DECIMAL(3,2) NOT NULL,
IDPeliFK INT NOT NULL,
IDSalaFK INT NOT NULL,
CONSTRAINT FuncionSalaFK FOREIGN KEY (IDSalaFK)
REFERENCES SALAS(IDSala),
CONSTRAINT FuncionPeliFK FOREIGN KEY (IDPeliFK)
REFERENCES PELICULAS(IDPelicula)
);
go
CREATE TABLE dbo.RESERVA (
IDReserva INT PRIMARY KEY IDENTITY (1, 1),
FecReserva DATETIME NOT NULL,
NumButaca INT NOT NULL,
IDUserFK INT NOT NULL,
IDFuncionFK INT NOT NULL,
PrecioNeto DECIMAL(3,2) NOT NULL, --Precio tras Descuento (premium?)
CONSTRAINT ReservaUserFK FOREIGN KEY (IDUserFK)
REFERENCES USUARIOS(IDUsuario),
CONSTRAINT ReservaFuncionFK FOREIGN KEY (IDFuncionFK)
REFERENCES FUNCIONES(IDFuncion)
);
go
CREATE TABLE dbo.COLABORADORES_LISTAS (
IDUserFK INT NULL,
IDListaFK INT NOT NULL,

CONSTRAINT ColaboUsuarioFK FOREIGN KEY (IDUserFK)
REFERENCES USUARIOS(IDUsuario),
CONSTRAINT ListaListaFK FOREIGN KEY (IDListaFK)
REFERENCES LISTAS(IDLista)
);
go
CREATE TABLE dbo.USUARIOS_AMIGOS (
IDUserFK INT NULL,
IDAmigoFK INT NOT NULL,

CONSTRAINT UsuarioUsuarioFK FOREIGN KEY (IDUserFK)
REFERENCES USUARIOS(IDUsuario),
CONSTRAINT AmigoUsuarioFK FOREIGN KEY (IDAmigoFK)
REFERENCES USUARIOS(IDUsuario)
);
go
CREATE TABLE dbo.LISTA_PELI (
IDListaFK INT NOT NULL,
IDPeliFK INT NOT NULL,

CONSTRAINT ListaListaFK FOREIGN KEY (IDListaFK)
REFERENCES LISTAS(IDLista),
CONSTRAINT PeliPeliFK FOREIGN KEY (IDPeliFK)
REFERENCES PELICULAS(IDPelicula)
);
go
CREATE TABLE dbo.PELI_TRABAJADOR (
IDPeliFK INT NOT NULL,
IDTrabajadorFK INT NOT NULL,

CONSTRAINT PeliPeliFK FOREIGN KEY (IDPeliFK)
REFERENCES PELICULAS(IDPelicula),
CONSTRAINT TrabajadorTrabajadorFK FOREIGN KEY (IDTrabajadorFK)
REFERENCES TRABAJADORES(IDTrabajador)
);
go
CREATE TABLE dbo.PELI_GENERO (
IDPeliFK INT NOT NULL,
IDTrabajadorFK INT NOT NULL,

CONSTRAINT PeliPeliFK FOREIGN KEY (IDPeliFK)
REFERENCES PELICULAS(IDPelicula),
CONSTRAINT TrabajadorTrabajadorFK FOREIGN KEY (IDTrabajadorFK)
REFERENCES TRABAJADORES(IDTrabajador)
);
go
