//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Astrofilm.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class AstrofilmEntities1 : DbContext
    {
        public AstrofilmEntities1()
            : base("name=AstrofilmEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<GENEROS> GENEROS { get; set; }
        public virtual DbSet<LISTAS> LISTAS { get; set; }
        public virtual DbSet<PELICULAS> PELICULAS { get; set; }
        public virtual DbSet<TRABAJADORES> TRABAJADORES { get; set; }
    }
}
