//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Astrofilm.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class COLABORADORES_LISTAS
    {
        public Nullable<int> IDUserFK { get; set; }
        public int IDListaFK { get; set; }
    
        public virtual LISTAS LISTAS { get; set; }
        public virtual USUARIOS USUARIOS { get; set; }
    }
}
