//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Astrofilm.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class CRITICAS
    {
        [Display(Name = "ID")]
        public int IDCritica { get; set; }
        public string Texto { get; set; }
        [Display(Name = "ID Usuario")]
        public int IDUserFK { get; set; }
        [Display(Name = "ID Pelicula")]
        public int IDPeliFK { get; set; }
    
        public virtual PELICULAS PELICULAS { get; set; }
        public virtual USUARIOS USUARIOS { get; set; }
    }
}
