//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Astrofilm.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FUNCIONES
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public FUNCIONES()
        {
            this.RESERVA = new HashSet<RESERVA>();
        }
    
        public int IDFuncion { get; set; }
        public System.DateTime Fecha { get; set; }
        public Nullable<int> Disponibles { get; set; }
        public decimal PrecioBruto { get; set; }
        public int IDPeliFK { get; set; }
        public int IDSalaFK { get; set; }
    
        public virtual PELICULAS PELICULAS { get; set; }
        public virtual SALAS SALAS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RESERVA> RESERVA { get; set; }
    }
}
