//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Astrofilm.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class PELICULAS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PELICULAS()
        {
            this.CRITICAS = new HashSet<CRITICAS>();
            this.FUNCIONES = new HashSet<FUNCIONES>();
            this.LISTAS = new HashSet<LISTAS>();
            this.GENEROS = new HashSet<GENEROS>();
            this.TRABAJADORES = new HashSet<TRABAJADORES>();
        }
    
        [Display(Name = "ID")]
        public int IDPelicula { get; set; }
        public string Titulo { get; set; }

        [DisplayFormat(DataFormatString = "{0:yyyy}")]
        public System.DateTime Año { get; set; }
        [Display(Name = "Puntuación Media")]
        public decimal PuntMedia { get; set; }
        [Display(Name = "Portada")]
        public string Imagen { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CRITICAS> CRITICAS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FUNCIONES> FUNCIONES { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LISTAS> LISTAS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GENEROS> GENEROS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TRABAJADORES> TRABAJADORES { get; set; }
    }
}
