//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Astrofilm.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RESERVA
    {
        public int IDReserva { get; set; }
        public System.DateTime FecReserva { get; set; }
        public int NumButaca { get; set; }
        public int IDUserFK { get; set; }
        public int IDFuncionFK { get; set; }
        public decimal PrecioNeto { get; set; }
    
        public virtual FUNCIONES FUNCIONES { get; set; }
        public virtual USUARIOS USUARIOS { get; set; }
    }
}
